### ISSUE TITLE
Consider automating a portion of Bug Triage work with a bot

### ISSUE THREAD

**Issue by jtslear** [kubernetes/sig-release#1009]
**What would you like to be added**:

During the lead up to Code Freeze, the Bug Triage teams' primary responsibility is following up on issues to ensure that they do not go stale.  Specifically this section of the runbook: https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/bug-triage#mid-release-cycle

This process should be able to be automated.  Issues contain all the necessary metadata:

* Issue status
* Assigned Milestone
* Assignees/Authors
* Wide swath of labels

I'd like to request that we bolster `fejta-bot`'s (or any bot) capability to tackle this particular procedure leading up to the code freeze.

Additional details required:

* What is the current milestone

Since it's not the primary responsibility of the Bug Triage team to make decisions, but rather ping the right people, we should be able to provide the above information for the bot to query the correct issues and send notifications in an effective manner.

I mention `fejta-bot` specifically as it appears to be the bot that operates without requiring user interaction.  If there is a better suited bot, let's ensure it is evaluated.

**Why is this needed**:

Doing so shifts the work of Bug Triage allowing the team to concentrate their efforts elsewhere.  If we can successfully implement the above proposal, we can potentially expound the efforts of the bot to include other functionality of the Bug Triage team, such as escalating to the appropriate SIG leads, clearing/moving milestones, etc.

**Comment by gianarb** [comment]
Hello! 

I am reporting here a conversation started over Slack. I like the idea to automate part of the bug triage recurrent workload but I think we have to be very careful about what and how because even if it looks repetitive to ping containers and contributors over and over an aseptic robotic message will not transmit the right message to maintainers and contributors working on their code. But I am sure we can figure out something or at least try to do so! 

The code for the automation we use leaves in the [https://github.com/kubernetes/test-infra/tree/master/prow/plugins/lifecycle](test-infra/prow/plugins). The lifecycle plugin is the one that marks stale issues as frozen.

What do we think are the criteria the bug triage team uses to decide when and who to ping in a issue or PR?

There is a combination of labels and milestone: `is:issue milestone:v1.19 -label:kind/failing-test -label:kind/flake` for example is the one we use to populate the spreadsheet with the list of issues to look after. So this identifies our responsibility.

The rules to figure out if it is the case to leave a comment or not, the tone, who quotes to are more tricky and I have to think deeply about them.

**Comment by droslean** [comment]
/cc @kubernetes/sig-testing 
@spiffxp Do you think that a prow plugin can manage this?

**Comment by LappleApple** [comment]
@droslean Might be what @sayanchowdhury was getting at during our recent release team prioritisation sessions, with this comment: "Should consider if we can have a prow plugin for this. The cost should be low and prow plugins are easy to implement."
