### ISSUE TITLE
Private Slack channel for Release Team Lead communications

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#1050]
#### What would you like to be added:

`#release-team-leads` channel in Kubernetes Slack with the following members:
- @onlydole (1.19 RT Lead)
- @mrbobbytables (1.19 RT Lead Shadow) 
- @jeremyrickard (1.19 RT Lead Shadow)
- @tpepper (subproject owner)
- @justaugustus (subproject owner)

#### Why is this needed:

Throughout the release cycle, we have a feedback loop between the RT Lead(s) and SIG Chairs that's strewn across multiple group DMs, which often need to be recreated.

I'd like a singular channel where we can maintain that communication.
Requesting this as private, as we often discuss personnel issues, and I don't believe that should be in a public forum.

Assigning some Slack admins:
/assign @alejandrox1 @jeefy @mrbobbytables @castrojo 
cc: @kubernetes/sig-release-admins @kubernetes/release-team-leads 

/milestone v1.19
/priority important-soon
/kind feature

**Comment by jeefy** [comment]
-1 from a Slack Admin. After some discussion, here are our problems (of varying degrees):

1. How is the release lead team different from any other team in the release process?
2. How much discussion amongst leads is really sensitive in nature?
3. What happens when a team rotates out and a new team rotates in and can see the previous teams' technically privileged conversations?

This is a case where group DMs still make the most sense from multiple perspectives.

On a personal note, from my perspective a significant amount of the convos here could/should be in a public forum and not in a group DM.

Other slack admins can/should chime in with their opinions.

**Comment by alejandrox1** [comment]
We discussed this with the idea that having a private channel for release lead, lead shadows, and sig chairs would replace the large group DM that is usually done.
In practice this would imply that at the beginning of a new cycle there is still work to be done adding and removing people from the private channel would be a similar amount of work as recreating group DMs.

As mentioned in the bullet point 3 above, if a personal matter is discussed, then the new team would have access to communications from previous release team leads which doesn't provide a lot of privacy.

**Comment by mrbobbytables** [comment]
I believe the conclusion was that we are a -1 on creating a leads channel.
