### ISSUE TITLE
Feature tracking spreadsheet enhancement ideas

### ISSUE THREAD

**Issue by mistyhacks** [kubernetes/sig-release#157]
I'm very new to the Kubernetes release processes, and as I try to understand the state of the 1.11 release from a docs perspective, I am facing some struggles with the feature tracking spreadsheet. After a conversation with @justaugustus , he asked me to open an issue here to try to capture some of the things that seem fairly actionable.

/assign @justaugustus 

1.  All the frozen rows on the top of the spreadsheet add little value and make the spreadsheet hard to use on any screen that is not huge. I can only see 3-4 actual data rows on my 13" MBP. Maybe this stuff can be put in a Metadata sheet instead, so people could click there to get the info but it is not persistent in the main view.

2.  We enumerate how many features are alpha, beta, and GA. It would be nice if there was a query that also pulled those rows out into one sheet per stage. Docs expectations (and probably testing expectations) are different for each of those stages, so it would be good to have a way to see, for instance, all the GA features.

3.  Speaking of alpha, beta, and GA, we are missing a piece of data that I think is important here too. I think it is important to know what stage a feature is moving FROM and what stage it is moving TO. I think right now we only capture what stage the feature will be in at GA. It's hard to see what features are truly new and what ones are moving to a higher level of maturity. I could imagine instances where we have things that start out at beta or GA, and things that start at alpha and then move straight to Deprecated, etc. If something is moving from Alpha to Beta, there may be some existing docs that just need to be updated. If it is a brand new feature though, it probably has zero docs.

4.  The links in the first column are confusing in two ways:
    - It is very hard to see the PR number or repo they are in, without actually clicking the link (the link text is obscured even on click / hover, because the links are so much longer than the column width of the sheet).
    - The links seem to usually go to the feature spec PR and not to the actual code PR(s). Yet it is the code PR owners who write the draft docs PRs and they reference the code PRs from the docs PRs. So with the info in the sheet now, it is really hard to map a docs PR to the relevant line item in this spreadsheet.

5.  If you mark a row as Docs Needed: Yes (or no) I do not see any way to turn it back into an unset value.

6.  It is unclear whose responsibility it is to update the "Docs Needed" and "Docs PR" fields. Whose job is it to determine if docs are needed for a given feature? Is it Docs or the feature owner? It makes sense that it would be the feature owner, since they are the ones who (to my understanding) submit the initial docs PR.

I think these are the things we talked about that are easily actionable. Please let me know if I missed anything.

**Comment by justaugustus** [comment]
Thanks for putting this up, @mistyhacks!
I'll start taking a look at some of this stuff tomorrow.

**Comment by idvoretskyi** [comment]
@mistyhacks I'm the initial creator of the features tracking spreadsheets for the last ~8 releases of Kubernetes, including the current one (1.11); happy to respond below:

> All the frozen rows on the top of the spreadsheet add little value and make the spreadsheet hard to use on any screen that is not huge. I can only see 3-4 actual data rows on my 13" MBP. Maybe this stuff can be put in a Metadata sheet instead, so people could click there to get the info but it is not persistent in the main view.

We needed to simplify the way of how the number of features is visualized (per-stage). I'm popen for suggestions how to fix it if the current way is uncomfortable.

> We enumerate how many features are alpha, beta, and GA. It would be nice if there was a query that also pulled those rows out into one sheet per stage. Docs expectations (and probably testing expectations) are different for each of those stages, so it would be good to have a way to see, for instance, all the GA features.

Not sure if I understood the value of this change. Can you please provide more thoughts and reasons?

> Speaking of alpha, beta, and GA, we are missing a piece of data that I think is important here too. I think it is important to know what stage a feature is moving FROM and what stage it is moving TO. I think right now we only capture what stage the feature will be in at GA. It's hard to see what features are truly new and what ones are moving to a higher level of maturity. I could imagine instances where we have things that start out at beta or GA, and things that start at alpha and then move straight to Deprecated, etc. If something is moving from Alpha to Beta, there may be some existing docs that just need to be updated. If it is a brand new feature though, it probably has zero docs.

Agree, progress tracking is heavily needed and long-awaited... Hopefully, we'll be able to implement it before the next release cycle (1.12)

> It is very hard to see the PR number or repo they are in, without actually clicking the link (the link text is obscured even on click / hover, because the links are so much longer than the column width of the sheet).

Originally, I did it to save space on the viewer's screen :)

> The links seem to usually go to the feature spec PR and not to the actual code PR(s). Yet it is the code PR owners who write the draft docs PRs and they reference the code PRs from the docs PRs. So with the info in the sheet now, it is really hard to map a docs PR to the relevant line item in this spreadsheet.

This is the goal of the features tracking spreadsheet - we are tracking data from the k/features repo, which is the original source of truth about the features in the release. We may add an additional column that links to the code implementation (eg. in k/k), but definitely, we shouldn't remove the links to k/features.

> If you mark a row as Docs Needed: Yes (or no) I do not see any way to turn it back into an unset value.

Google Sheets UI limitation. But why may we need these values unset? :)

> It is unclear whose responsibility it is to update the "Docs Needed" and "Docs PR" fields. Whose job is it to determine if docs are needed for a given feature? Is it Docs or the feature owner? It makes sense that it would be the feature owner, since they are the ones who (to my understanding) submit the initial docs PR.

It has to be codified, as it's really unclear for many of us. When we've added this column to the spreadsheet a few releases ago, it was a result of collaboration between the features lead (me) and the docs lead.

...

Thank you for your huge feedback, the current features tracking process can be heavily enhanced based on it or the similar inputs. For historical reasons, the spreadsheet was primarily manually maintained by the single person (me), starting from 1.11 @justaugustus helps us a lot. The feedback and enhancement suggestions are absolutely welcome!

**Comment by mistyhacks** [comment]
I'll address your questions in chunks.

#1: I think you could use a single row with multiple columns to visualize alpha / beta / GA features. That would take save 3 rows. In a similar way, I'm not sure the spreadsheet maintainers really each need their own rows. :) It also seems like it would be just as easy to visualize them if the chart of alpha / beta / GA was on a different sheet in the same doc. You could even do something like compare it to the previous release's metrics, to try to gain insights on relative size of releases. **I did a test of a simple formatting change in a duplicate sheet called "Misty's Test". Feel free to have a look and then delete the sheet.**

#2: This partially relates to progress tracking, which I'm happy you agree is needed! In addition, we might have certain expectations about what a feature needs to be considered complete for Alpha, Beta, or GA.  Maybe it's acceptable for an Alpha feature to have no docs, in which case the Docs PR fields might plausibly be blank. That contract might be different for GA features. It might be useful, therefore, to be able to get a list of just ALpha features or just GA features, visually. It's inefficient to have to scroll up and down 40+ lines and spot the differences. It seems like with spreadsheet trickery it could be done in a relatively low-maintenance way.

#3: Happy to hear this!

#4. Oh the irony!

#5: I agree, the links shouldn't be removed. It's just hard for me to map them to a docs PR. Maybe we . can socialize the code implementors to link from their PR to the feature doc PR.

#6: In case someone (me) accidentally sets the value. It turns out you can just clear the field, in the upper area where you would type formulas.

#7: Any ideas how we can help codify it?

Thanks for taking so much time to give me more background!

**Comment by justaugustus** [comment]
Hey @mistyhacks!

I made some improvements to the sheet, based on your suggestions...

> I think you could use a single row with multiple columns to visualize alpha / beta / GA features. That would take save 3 rows. In a similar way, I'm not sure the spreadsheet maintainers really each need their own rows. :) It also seems like it would be just as easy to visualize them if the chart of alpha / beta / GA was on a different sheet in the same doc. You could even do something like compare it to the previous release's metrics, to try to gain insights on relative size of releases. I did a test of a simple formatting change in a duplicate sheet called "Misty's Test". Feel free to have a look and then delete the sheet.


* Removed the Alpha / Beta / Stable / Total area on the `Features list` (this is strictly in the `Features stats` sheet now)
* Updated the `Features stats` sheet to use the more appropriate function you suggested for `COUNTA`
* Updated the SIGs, so `Features per SIG` is now accurate
* Moved the Docs stats over, so it's less disruptive to add more SIGs, when we need to
* Refroze the main columns. Take a look and let me know if it's still readable from your laptop.

I took a look at your sheet, and it looks like I did something close to what you had in mind. Let me know if it's still okay to delete that test sheet.


> This partially relates to progress tracking, which I'm happy you agree is needed! In addition, we might have certain expectations about what a feature needs to be considered complete for Alpha, Beta, or GA. Maybe it's acceptable for an Alpha feature to have no docs, in which case the Docs PR fields might plausibly be blank. That contract might be different for GA features. It might be useful, therefore, to be able to get a list of just ALpha features or just GA features, visually. It's inefficient to have to scroll up and down 40+ lines and spot the differences. It seems like with spreadsheet trickery it could be done in a relatively low-maintenance way.


The features list has a filter that would allow you to sort and filter out extraneous rows when needed. I think that's sufficient to cull the data without duplicating the data, but let me know if you feel differently.

The sheet in general is for mapping feature issues; if we're concerned about the contract for docs at each stage, I think we need to make sure we're getting that contract documented and socialized to anyone who might own / open features.


> I agree, the links shouldn't be removed. It's just hard for me to map them to a docs PR. Maybe we . can socialize the code implementors to link from their PR to the feature doc PR.


I've updated all of the links so that they're now prepended with the feature number. 
I completely agree that we should socialize every feature PR should have a link to a docs PR, and the actually implementation PRs. Thoughts @idvoretskyi?


> In case someone (me) accidentally sets the value. It turns out you can just clear the field, in the upper area where you would type formulas.


Just want to confirm that you're actually [still] able to to [un]set these values.


> Any ideas how we can help codify it?


I think that it should be the responsibility of the Feature owner to update the `Docs Needed` and `Docs PR` fields. RT Docs personnel should follow up with the Feature Owner occassionally, but as stated in [k/features](https://github.com/kubernetes/features/#when-to-create-a-new-feature-issue), features should be created

> once you... are ready to be the project-manager for the feature

If that's not happening as it should, we should make strides to better define the Feature creation process. Thoughts @idvoretskyi?


---

In addition to some of the improvements mentioned, I've also done a bit of a feature sweep.

Part of that included creating a new sheet called `Milestone risks`, which includes a set of Feature issues which could be at risk of or have been removed from the milestone.

Here are some of the statuses that will give you a quick indicator of Feature progression / risk:
* *Needs RT review:* should be reviewed by a member of the Release Team
* *Removed:* fit some criteria to be removed from the milestone
* *Docs overdue:* Issue was marked as needing docs, but a docs PR has not yet been supplied
* *Milestone slip:* fit some criteria to be removed from the milestone, but I'd like to check in with the Feature Owner or RT Lead before doing so
* *TBD:* No status, but requires a follow-up


@jberkus -- take a look at those and let me know what you think.

**Comment by jberkus** [comment]
So, this is some musing around the information we've needed on features this cycle.  It's not a list of specific corrections or revisions.

- Feature has a PR
- Feature's PR is approved
- Feature has tests
- Feature is linked to failing tests
- Feature has bug issues
- Feature has a Docs PR
- Feature's  has a full first draft of Docs
- Has final docs
- Already had docs from a prior release which do need updating
- Has docs from a prior release which don't need updating
- Feature is being bumped to a later release

So one thing I can see already is that the "Needs Docs" tab needs more discretion, since it has potentially four states: Yes, None Needed, Needs Updating, Already Has

**Comment by jberkus** [comment]
If I was to do this as a set of database fields, they would be:

* Feature Status: Planned, Late, In Progress, In Trouble, Complete, Deferred
* PR Status: None, Partial, In Progress, In Trouble, Merged
* Needs Docs: Unknown, Yes, None Need, Needs Updating, Already Has
* Docs Status: N/A, Has PR, Draft, Late, Complete
* Exception?  (link)
* Test Status: Needs Tests, Partial, Complete.
* Failing Tests?  (links)

... and, of course, links to PRs for all of these things.  Note that some features will have multiple PRs, both for code and for docs.

**Comment by jberkus** [comment]
Also, we should give some thought to tracking multi-PR "big" features as opposed to tracking single-PR features.

**Comment by justaugustus** [comment]
@jberkus -- This is all really awesome insight; thanks!
I'll see what we can work into the sheet.

**Comment by mistyhacks** [comment]
This all looks great, and I agree with @jberkus assessment. Thank you so much! I've deleted my sheet now.

As an aside, I avoided re-sorting the main sheet because I've seen some people refer to items by line number in the sheet (and I have also done so), and I wasn't sure if the sorting would be visible to other viewers of the sheet. If it's "safe" to sort and filter that way, I am happy to do that.

**Comment by justaugustus** [comment]
@mistyhacks -- fair point. I think as long as you're returning the filter to display all data once you're done, I'm fine with it. :)

As for this issue, I'm going to close it out. I think we've incorporated most of the suggestions you've made. Let me know if we need to reopen for any reason.

/close
