### ISSUE TITLE
Add systemd periodic job to release-informing and systemd presubmit job release-nonblocking

### ISSUE THREAD

**Issue by harche** [kubernetes/sig-release#1608]
## Summary

- Make NodeConformance periodic job that uses systemd cgroup driver release-informing
- Make NodeConformance presubmit job that uses systemd cgroup driver release-nonblocking

## Motivation:
Kubelet supports ‘systemd’ cgroup driver. This part of the code needs to be thoroughly tested against incoming changes to make sure no new changes end up breaking existing supported functionality. 

In the past, we have seen a number of regressions in the existing crio/systemd presubmit and periodic test jobs runc, caught later by periodic jobs, https://github.com/kubernetes/kubernetes/issues/102092. Another example of minor regression that was caught by these test jobs which affected systemd driver, https://github.com/kubernetes/kubernetes/issues/101311 The frequency of changes breaking the crio periodic jobs suggests they will be a good candidate for presubmits.

### Contact person -
 Harshal Patil - harpatil@redhat.com

### Existing Results 
https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-conformance (periodic)
https://testgrid.k8s.io/sig-node-cri-o#pr-crio-gce-e2e (presubmit)

## PR 
https://github.com/kubernetes/test-infra/pull/22507
https://github.com/kubernetes/test-infra/pull/22740

/cc @saschagrunert

**Comment by saschagrunert** [comment]
@kubernetes/ci-signal what are your thoughts on adding the jobs to [`sig-release-master-informing`](https://testgrid.k8s.io/sig-release-master-informing) with keeping in mind that they should graduate to `sig-release-master-blocking`? Maybe this is a good chance to [update the docs](https://github.com/kubernetes/sig-release/blob/master/release-blocking-jobs.md#release-blocking-jobs-and-criteria)?

Right now they state:
> If you want to add a Blocking job, please ask to add them to the appropriate Informing dashboard first. The release team can later decide if the test should be moved to the Blocking dashboard.

**Comment by neolit123** [comment]
i recall discussions that CNI / CRI implementors should have periodic  or PR blocking signal that verifies if the k8s versions in scope for their releases (matrix) work on their end.

if k8s starts blocking release on interface implementors the matrix becomes complex and there is high chance for test jobs to become stale and unmaintained. some CNI plugins are already doing that. by testing the tip of k/k branches, failure signal propagation should get sufficient attention and as long there are maintainers to log the issues and label them properly so that the release team can make a decision to block a release.

**Comment by BenTheElder** [comment]
I think the concern here is that we do not have coverage running with the systemd codepaths in kubelet today, so someone must setup CI for this. In this case they have also done so with another vendor implementation that was not in CI.

This should be going CI job => informing => blocking.
It should be proven to be stable in informing before going to blocking.

I believe this was already added to blocking presubmit, so I will take this opportunity to reiterate that doing so should *not* have happened before creating a stable release blocking equivalent, and then promotion from manual presubmit => run but not blocking or reporting => blocking + reporting. Once we have a release blocking job we have data that:
- The job itself is a reliable signal and not flaky
- The job is catching frequent issues from bad PRs and therefore justifies yet another (expensive!) presubmit that PRs must contend with
Given evidence of those, it can be in presubmit as well.

https://github.com/kubernetes/sig-release/blob/master/release-blocking-jobs.md has detailed criteria for PR blocking.
There's an open issue to write down the PR process, though we also *highly* discourage new presubmits in general and have been focused on cutting down on the glut of Kubernetes presubmits https://github.com/kubernetes/test-infra/issues/18729

I have a separate nit that this are not consistently named, "gce-e2e" to me says cluster e2e, it's not obvious that these are equivalent node-e2e jobs but with cgroupsv1 vs cgroupsv2.

> https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-conformance (cgroup v1)
> https://testgrid.k8s.io/sig-node-cri-o#pr-crio-cgrpv2-gce-e2e (cgroup v2)

Is systemd cgroups but cgroupsv1 a configuration we need to be covering? On PRs in particular the matrix of (CRI, cgroups) is a bit excessive to have individual presubmits. We have blocked doing the same for e.g. (cluster type, IPv4 vs IPv6 vs DualStack), we have a single IPv6 PR job because we had evidence of frequent breakage of IPv6 specific codepaths due to e.g. naive concatenation of IP + ":" + port. We did not setup the full matrix for similar concerns about excessive test matrix.

**Comment by saschagrunert** [comment]
@kubernetes/ci-signal I'd like to ping you again for consensus on this one.

**Comment by lambdanis** [comment]
I see both jobs are running quickly and often, that's good.

There was a single flake of `ci-crio-cgroupv1-node-e2e-conformance` on July 10th 2021: https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-conformance&width=20 Any idea what might be the reason? I don't have major concerns against adding it to release-informing dashboard though.

`pull-kubernetes-node-crio-e2e` has multiple flakes without any build log, like https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-node-crio-e2e/1414934905959223296. There were also some timeouts. But most builds are passing, so if it's non-blocking then I guess it's ok?

**Comment by haircommander** [comment]
@lambdanis that [failure](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv1-node-e2e-conformance/1413964708880322560) seems to be https://github.com/kubernetes/kubernetes/issues/100788 which is known and applies across the node e2e tests

**Comment by ehashman** [comment]
> This should be going CI job => informing => blocking.
> It should be proven to be stable in informing before going to blocking.

Agreed.

We have been working on an overall plan for promoting these jobs, and we will share in the SIG Node CI subproject next week and then with wider SIG Release/SIG Testing. (More [slack context](https://kubernetes.slack.com/archives/C2C40FMNF/p1626299372136700?thread_ts=1626286914.123500&cid=C2C40FMNF).)

> I believe this was already added to blocking presubmit, 

That was reverted :)

**Comment by BenTheElder** [comment]
> > I believe this was already added to blocking presubmit,
>
> That was reverted :)

Thanks, the rest of what follows the excerpt quoted covers what should happen before introducing it there next time, which seems related to this thread.

I also have some questions at the end of that comment that I can't answer yet.

**Comment by jeremyrickard** [comment]
Let's solicit any additional feedback from CI Signal and use this to shape a process for #1611

**Comment by ehashman** [comment]
This does not appear to have moved... 

/assign @encodeflush 
current CI Signal Lead

**Comment by harche** [comment]
Closing it since https://github.com/kubernetes/test-infra/pull/22507 is merged. 

/close
