### ISSUE TITLE
Archive meeting notes for Kubernetes SIG Release meeting

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/sig-release#2255]
We're observing performance issues when loading Google doc with meeting notes for the Kubernetes SIG Release meeting. The doc has meeting notes since 2017 so we should consider archiving those notes.

We discussed this on SIG Release meeting held on 2023-05-16 and it has been decided to proceed with this idea.

Other SIGs are doing something similar including [SIG Contribex](https://github.com/kubernetes/community/tree/master/sig-contributor-experience/meeting-notes-archive) and [SIG Docs](https://github.com/kubernetes/community/tree/master/sig-docs/meeting-notes-archive).

Similar to those two SIGs, we should archive per year. If needed, we'll reconsider this and archive every half a year.

/sig release
/priority important-longterm
/triage accepted
/assign @jimangel

**Comment by RohanSasne** [comment]
Hey, if there's a scope, can i help @jimangel with archiving the notes? 

I would love to contribute to the PR for this issue @xmudrii

**Comment by jimangel** [comment]
A couple notes that I want to keep track of:

- I downloaded a full backup of the notes (1.7mb)
- After removing <2023 content, it was 900kb (surprised it was still largish)
- I removed an image I passed in (didn't add value and is from recording) and it reduced 100kb
- After googling, it turns out the exported doc includes downloaded fonts, so I made everything use Arial, and it brought the exported size to 500kb

The doc still "feels" sluggish to me, but it might be all the work I was doing / local internet. We'll see if it "feels" better on the next call!
