### ISSUE TITLE
Define process and doc for release shadow/lead removal

### ISSUE THREAD

**Issue by gracenng** [kubernetes/sig-release#2332]
### What would you like to be added:

- [x] Documentation for shadow removal criteria and process
- [x] Documentation for role lead removal criteria and process ( + how other SIG can be involved in the process)
- [ ] Define the process for leads to reachout to "warm pool" of contacts in the event of removal

### Why is this needed:
- tl;dr: release team member drop-off happens every release. Without an official removal process, folks who stay on the team without contributing creates an unfair environment for those who put in the work, and negatively affect the outcome of the release. Note that graceful resignation will continue to be appreciated, this issue is about unresponsive and non-performing members.
- This is the action item from our [1.28 retro meeting](https://bit.ly/k8s128-releasemtg)
- Related to: https://github.com/kubernetes/sig-release/issues/2127#event-8791241644
- Draft PR in progress: https://github.com/kubernetes/sig-release/pull/2322

#### Shadow Removal

1. Reasons
- Failure to attend shadow orientation hosted by EA (we host 2-3 sessions in different timezone)
- Failure to attend shadow orientation hosted by role lead (if lead doesn't offer timezone-appropriate meeting, shadow should communicate to lead about obtaining and watching the recording)
- Failure to attend 2 consecutive release meeting without communication to role lead
- Failure to perform shadow tasks in due time, after 2 discussions with role lead about performance
- Unresponsive on Slack to messages for more than 2 days during non-peak time and 24 hours during peak time, without prior notice of absence. Peak time is different depending on team.
3. Process
- Upon a pattern of inactivity, role lead will notify EA and have initial discussion with shadows about performance.
- If the shadow is still not contributing to the team, EA and lead will remove shadow from team, and find replacement if appropriate. EA will be responsible to find backfill.
4. Consequences:
- If the current release is the reason the shadow obtain Kubernetes membership, membership should be revoked
- Removal of name in release-team document
- If removed and not resigned, shadow will not be able to return to the following release

#### Role Lead Removal

1. Reasons
- Failure to attend or send appropriate representation to 2 consecutive release meeting
- Failure to perform tasks expected of role lead
- Unresponsive on Slack to messages for more than 2 days during non-peak time and 24 hours during peak time, without prior notice of absence. Peak time is different depending on team.
3. Process
- SIGs outside of SIG-release, shadows, leads, or contributors can express concern to release lead or EA.
- Release lead and EA will have initial discussion with role lead
- If the situation is not improved, release lead and EA will have another discussion with role lead and begin to look for replacement.
- If deemed necessary by release lead, EA and sig-release chairs, role lead will be replaced with an experience shadow or someone who previously lead the same role. EA will be responsible to find backfill.
4. Consequences
- Removal of name in release-team document
- If removed and not resigned, lead will need to shadow again and demonstrate sufficient responsibility, and leading ability, before holding another lead role

cc @leonardpahlke @Priyankasaggu11929 @salaxander @kubernetes/sig-release-leads 
@natalisucks @divya-mohan0209 @reylejano @katcosgrove @mickeyboxell

**Comment by leonardpahlke** [comment]
Thanks for opening this issue, Grace, great summary. This is needed!

I think the discussion about the shadow removal process is very necessary, since a few people drop out every cycle and this discussion is held at the end of every release. The process of removing a lead on the other hand is a bit odd to me, as we haven't had that problem yet - yes, there are sometimes leads that aren't as active as others, but we've never had to deal with the problem of replacing a lead. Nonetheless, this can also be defined (but I don't think it's necessary, as I'm always hesitant to establish processes and define things that aren't necessary).

> **Shadow Removal**
> 3. Process
> ...
> EA will be responsible to find backfill.

In my experience, the shadows quietly disappear in the middle to the end of the release cycle. I am not a big fan of onboarding folks halfway through the release. This would require a lot of extra work (adding them to all required files, setup orientation and onboarding sessions, maybe another get to know the team meeting etc.)

**Comment by natalisucks** [comment]
@leonardpahlke In the last release retro (held during the regular SIG Release meeting on Tuesday, Aug 29), the discussion around replacing leads was had due to the recent experience with 1.28 and an unresponsive lead, where shadows took over for a portion of time. As noted in that meeting, the combination of Release Team roles being a resume builder within the industry, plus the friction felt by SIGs when lead unresponsiveness occurrs, called for there being a process put in place. As a SIG Co-chair who has experienced that friction, I believe the process is indeed necessary, and the retro yielded many folks in agreement with us kick-starting the work to define that process.

@gracenng A huge thank you for putting this issue together as a result of the retro discussions. I like the idea of the shadow/lead being able to "improve" the behaviour and possibly work to keep their role, with continued failure to do so resulting in their removal. After all, life happens and sometimes circumstances are outside of our control. I wonder if we need to further underline that shadows, while unable to come back to the next release if removed, could possibly re-apply in future, and what an application with better contributor behaviour could look like? That might be worth documenting in a separate issue.

**Comment by leonardpahlke** [comment]
Okay, sounds good. Let's think about a process. First up, I think we've made changes in a few places to increase the likelihood that we'll pick the right shadows as team leads for the upcoming cycle. I am optimistic we don't have to deal with this issue soon 🤞. But I see that this role of leading an open source team is a new experience for most, and not everyone is suited for it, which becomes apparent during the release cycle. So +1, putting a process in place to manage problems with team leads.

I would advocate for defining a softer process for team leads in comparison to shadows and allowing the release lead to manage the situation in their style. To me, it should not be like if you collect three complaints: you are done or if you are unresponsive for three days in a row: you are in big trouble. Removing a team lead from the release team can definitely be an option and needs to be an option if, for example, something happens and the team leads is unable to work on the team any longer (personal reasons or perhaps violates the CNCF CoC or so). What are your thoughts on giving the release lead a guide on hand how to resolve this situation which is not definitive but gives the lead the option to remove someone from the team.

**Comment by Princesso** [comment]
For shadows, the documented process looks good to me. 
When a shadow is removed from the Kubernetes org, what happens if they reapply to be a shadow in the future?

For leads, I want to believe that one only attains the lead status after successfully being a shadow; hence, it might not be a communication problem. I think leads should be allowed to willingly resign.

How about the idea of co-leads? That way, one person is only partially burdened with leading a team. Also, if a lead slacks, the co-lead can pick up from where the lead left off. This should probably be another issue.

**Comment by gracenng** [comment]
thanks for your feedback @Princesso!

for shadow, i like someone's suggestion above that the shadow is effective not allowed to return to the release team for the subsequent release. after that, they can reapply.

for lead, shadowing is the only way to become lead. however, we've noticed even that can still result in failure to perform their duties. in both cases, willingly resign is always allowed.

we have shadows who return to the same team and can serve as additional help. however, since the team is only 4-5, we often ask the lead to only have as many as they can mentor. it is not a burden, but a privilege and responsibility to lead a team.

let me know if everything here makes sense, thanks for taking the time to review

**Comment by Princesso** [comment]
Thanks for providing more clarity.
I understand your point of view now and I think the documented process totally makes sense.

Do you think the idea of having co-leads makes sense? To mitigate the risk of a lead dropping off within a release cycle. The co-lead can be one of the shadows who has previously served as a shadow on the same team.

**Comment by gracenng** [comment]
Personally, I think the team is small enough (4-5 ppl) that having 2 leads doesn't make sense. Lead can always ask for help from experienced shadow. I'll leave that idea open and see what other folks think

**Comment by jrsapi** [comment]
Regarding "3.Process" : Should an appeal process to SIG-Release chairs be in place if the role leads disagrees with the decision by the Release lead and EA?

**Comment by gracenng** [comment]
hi @jrsapi - great callout there. I can add:
- in the EA handbook: EA shall inform SIG-Release chair the event of release team member removal
- in this document about process: role leads or the member can request a review from SIG chairs

**Comment by gracenng** [comment]
Addressed in https://github.com/kubernetes/sig-release/pull/2322 so closing this. Let me know if there's anything I missed.
