### ISSUE TITLE
The stage of enhancements are marked wrong in enhancement tracking board

### ISSUE THREAD

**Issue by cici37** [kubernetes/sig-release#2513]
#### What happened:
The stage of enhancements are marked wrong in enhancement tracking board.

The stage of KEP is supported to get from the issue label but it shows wrong for multiple KEPs now.

e.g. https://github.com/kubernetes/enhancements/issues/4006 has the label of stage/beta but shows stable in enhancement tracking board: https://github.com/orgs/kubernetes/projects/183/views/1?filterQuery=4006

/cc @salehsedghpour

#### What you expected to happen:
The stage of KEP is fetched from the issue label and shown correctly.

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by salehsedghpour** [comment]
Based on my understanding and experience, the procedure is manual. But I feel that it could be tricky too, because sometime the enhancement have opted-in label first and then after sometimes the stage label gets added. 

And the enhancements team is making sure that the labels are correct according to the [handbook](https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/enhancements#before-enhancements-freeze).

What do you think @sreeram-venkitesh?

**Comment by sreeram-venkitesh** [comment]
@cici37 Thanks for creating the issue! As @salehsedghpour mentioned, adding the labels in the enhancements tracking board is done manually by the release enhancements team. Sorry for the mistake, we'll make sure that the labels match with the stage marked in the tracking board.

**Comment by sreeram-venkitesh** [comment]
@cici37 We've updated all the KEPs in the tracking board with the right stage, except for 3 KEPs related to DRA and https://github.com/kubernetes/enhancements/issues/2400, which has multiple alpha/beta stages and there is some confusion. I've reached out to the the assignees of these KEPs. Once these too are sorted, we can close this issue.

**Comment by sreeram-venkitesh** [comment]
We can close this now since the board is up to date.

/close
