### ISSUE TITLE
Assemble Kubernetes 1.32 Release Team 🚀🕐🎊🐕

### ISSUE THREAD

**Issue by Priyankasaggu11929** [kubernetes/sig-release#2586]
Hello everyone!

We're just a week and a half away from the planned 1.31 release, and it's time to start assembling the 1.32 Release Team! 🎉

Thank you all, especially the 1.31 Release Team shadows, for your hard work over the past few months. We couldn't have made it here without you! :heart: 

Please use this issue to nominate the lead for your role on the 1.32 release team.
Take a look at the [Release Team Selection Process docs](https://github.com/kubernetes/sig-release/blob/master/release-team/release-team-selection.md) for details on the process and criteria.

Once role leads are nominated, the upcoming Emeritus Advisor will send out the shadow application survey for selecting 1.32 shadows.

/sig release
/area release-team
/milestone v1.31
/kind documentation
/priority important-soon
/assign @Priyankasaggu11929

**Comment by Priyankasaggu11929** [comment]
It has been an absolute honor to serve as the Emeritus Advisor and to work with such amazing people during the 1.31 release cycle. Thank you, everyone! :heart: :pray: 

I am more than happy to announce @katcosgrove as the v1.32 Emeritus Advisor.

Kat has been, and continues to be, a tremendous influence on the Release Team with her extensive experience across multiple kubernetes release cycles and various other roles in the community!

**Comment by sreeram-venkitesh** [comment]
Hi folks! Leading the Enhancements team for v1.31 has been an honor! 

I'd like to give a big shoutout to all enhancements shadows @dipesh-rawat @ArkaSaha30 @mickeyboxell @prianna @tjons! Y'all have been working really hard this cycle and it really showed! 

I'm nominating @tjons as the Enhancements Lead for v1.32! Tyler has been in the team from v1.30 and is doing some great work to improve the processes of the enhancements team 🎉 

Huge thanks to @Priyankasaggu11929 and @neoaggelos for their mentorship and guidance. I've learnt a lot from you two! Also big thanks to the previous enhancements leads @salehsedghpour and @npolshakova, I wouldn't have been able to do this if not for working with you folks 🤩  

Congrats to everyone who was part of the v1.31 release! See you all around in future releases :) 

/honk

**Comment by tjons** [comment]
Hi everyone - I've had a great experience working with all of the 1.31 release team! @Priyankasaggu11929 and @neoaggelos thank you for leading us through the release as a team - your help has been invaluable. 

Thank you @sreeram-venkitesh for being an excellent Enhancements lead! I have learned a lot from your guidance and constant willingness to jump on a call, make things better, and keep the team moving forward. 

Thank you to my fellow Enhancements shadows - @dipesh-rawat @ArkaSaha30 @mickeyboxell and @prianna - you all have been excellent to work with and I hope to continue to collaborate with you in sig-release and elsewhere. 

I am honored and excited to lead the Enhancements team through the next release! 

/honk

**Comment by npolshakova** [comment]
Serving on the 1.31 Release Team has been an incredible experience! 🥳 🚀

It was an honor to serve as the Release Notes Lead this cycle, and I was fortunate to have an outstanding shadow team. A huge thank you to @satyampsoni, @cloudmelon, @shecodesmagic, @Checksumz, and @rayandas for your availability, hard work, and dedication in getting all the Release Notes PRs out on time! You're all super-stars! 🤩

A special thanks to @Priyankasaggu11929 and @neoaggelos for their guidance and support throughout the release cycle. I also want to give a shout-out to the previous Release Notes Lead, @rashansmith, for mentoring me during the last release and helping me transition into this role at the start of 1.31. Thanks as well to @fsmunoz and @sanchita-07 for being invaluable resources whenever any release notes-related questions arose!

I’m excited to nominate @satyampsoni as the Release Notes Lead for v1.32! Satyam has been a key member of the release notes team since 1.30, consistently going above and beyond in his work on the release team—whether it's creating the early release notes PRs, debugging krel, or assisting other team members.

A huge congrats to everyone on the v1.31 release! 

/honk

**Comment by satyampsoni** [comment]
Hello everyone,Working with the 1.31 release team has been an amazing experience! A huge shoutout to @Priyankasaggu11929 and @neoaggelos for your leadership and support throughout the release.

 Your help has been truly invaluable.Special thanks to @npolshakova for your exceptional leadership as the Release-Notes lead. Your guidance, willingness to jump on calls, and efforts to improve our processes have taught me so much.

To my fellow release notes shadows—@Checksumz , @shecodesmagic , @cloudmelon , and @rayandas —it's been fantastic working alongside you. 

I'm honored to take on the role of leading the Enhancements team for the next release!

/honk

**Comment by wendy-ha18** [comment]
Hi team,

Congratulations on our successful 1.31 release! It's been an incredible honor to work alongside all of you 🥂🚀🚀👏

Thank you for giving me the opportunity to learn from everyone and serve as a Release Signal Shadow for 1.31 release. A special shoutout to @Vyom-Yadav , our amazing Release Signal Lead, for his unwavering dedication and guidance. I can't even count the number of times Vyom backed us during the release cut or day-to-day monitoring of the test grid. I’ve learned so much from you.

I also want to give a big shoutout to my fellow teammates on the Release Signal team—@drewhagen, @sanchita-07, and @AdminTurnedDevOps. It’s been a pleasure working with you.

And last but certainly not least, thank you to @neoaggelos and @Priyankasaggu11929 for your leadership and support since my first week. If the APAC Release Team meeting hadn’t rolled out during the 1.31 release, I might not have been able to join the Release Team from Australia. Thank you for opening this door.

Finally, a big round of applause to @mehabhalodiya , our Branch Manager, for all her hard work.

Happy release day, everyone! I hope to see you all around in the K8s community and in the next releases.

Cheers,
/honk

**Comment by a-mccarthy** [comment]
Hi all, it was an honor to be a part of the 1.31 release and work on comms. Thank you to @neoaggelos and @Priyankasaggu11929 for leading us through this release and to @katcosgrove for offering a lot of support and guidance along the way, especially for all my comms questions ❤️ 

A huge shoutout to all the 1.31 comms shadow, @edithturn @hailkomputer @rashansmith and @mbianchidev, for all your  hard work and dedication this cycle! I was lovely working with you all. 

I'm happy to nominate @mbianchidev as the comms lead for 1.32. Although new to the release team in 1.31, Matteo showed great initiative to learn the comms processes, help team members, and keep us on track throughout the release.

**Comment by neoaggelos** [comment]
Hi folks, I am usually not a person of many words, but it was an absolute honor and a blessing to lead the release team for the v1.31.

Many many thanks to @katcosgrove, @gracenng, @Priyankasaggu11929 for their constant mentoring and continuous support. You know more than anyone how much you helped, and I am forever grateful for that.

Also congrats to all of the sub-team leads @sreeram-venkitesh, @Vyom-Yadav, @npolshakova, @a-mccarthy, @Princesso, whose hard and focused work made this release smooth.

A separate highlight to my release lead shadows, @drewhagen, @fsmunoz, @sanchita-07, and @salehsedghpour. Each of them stepped up to the challenge throughout the release, and their help was instrumental in the process.

Finally, I feel obligated to mention and extend a very public thank you to @soumplis, @kos.tsakalozos, @yalton-ruiz and @AlexsJones, without whose gratuitous guidance, mentorship and support, this would not have been possible.

I am very excited and proud to nominate @fsmunoz as lead for the v1.32 release! Frederico has been a staple of the team in numerous roles, and he is more than capable of taking the helm!

Χαιρετε!

/honk

**Comment by fsmunoz** [comment]
I've got very little to say that you haven't heard before, and yet I will say it anyway. 

I can still vividly remember starting as a shadow for Comms in 1.25, under @katcosgrove lead (which I'm lucky enough to have as EA now), and very, very far from thinking that I would continue to be involved in the release process, less alone that I would be nominated to lead one.

I've learned a lot from everyone at every cycle, and the last two ones as a Release Lead shadow have been exciting. I can only thank @neoaggelos for his great work in 1.31 and the vote of confidence, which I will do my very best to deserve.

I must say that I'm already a bit nervous about it, but then I look and see the people around me and, well, we'll be alright after all :heart:

**Comment by Vyom-Yadav** [comment]
It's been a pleasure working on the release team again! Congratulations to the new leads! Kudos to my fellow release signal team members @drewhagen @sanchita-07 @AdminTurnedDevOps and especially @wendy-ha18 (for doing great work during the cycle) on getting a quality release out of the gate. Shoutout to the release manager, @mehabhalodiya, for all the work she has put in as the release manager. 

I'm excited to announce that @drewhagen will be the release signal lead in 1.32. Drew was a part of the CI Signal team in 1.27 and was also involved with the team this cycle as a lead shadow 🚀 

Thanks to @neoaggelos and @Priyankasaggu11929 for leading this cycle 🙌🏼 and last but not least, thanks to all the folks who wrote code/docs for K8s, without which we wouldn't be releasing anything! To 1.32 🚀

**Comment by Princesso** [comment]
Hi everyone,

It was an absolute pleasure working with everyone on this team. Congratulations to the release leads @neoaggelos and @Priyankasaggu11929 for spearheading this release, despite the many challenges we faced this cycle. 

Shoutout to the Docs Shadows @chanieljdan, @hacktivist123 @salaxander @MaryamTavakkoli @LaurentGoderre. You all went above and beyond to make this cycle smooth. Even when I fell ill, I had no doubt that you would continue in the foundation that had been laid.

Special shoutout to @drewhagen and @katcosgrove, for holding the fort while I was at the hospital. I appreciate your dedication and continued support to the Docs team.

I am excited to announce that @chanieljdan will be the docs lead for the 1.32 release cycle. Daniel was a part of the Docs team in the v1.30 and v1.31 release cycles and has demonstrated a great sense of ownership, curiosity, and dedication needed to lead the Docs team. I have no doubt that Daniel will lead the Docs team effectively, in the coming cycle.

/honk

**Comment by saschagrunert** [comment]
@Priyankasaggu11929 can we close this issue?

**Comment by Priyankasaggu11929** [comment]
yes :)

/close
