### ISSUE TITLE
Decide on criteria for grouping release tests into blocking/informing/extra

### ISSUE THREAD

**Issue by jberkus** [kubernetes/sig-release#405]
Post-1.13, we need to complete the re-organization of the sig-release test boards into a proper blocking/informing/extra setup.  These would be the general criteria:

**blocking:** jobs that must pass for a release to take place, and [meet all of the blocking criteria](https://github.com/kubernetes/sig-release/pull/346) for reliability, ownership, and frequency.

**informing**: jobs that often supply useful information about breakage in the release, but fail to meet one of the criteria for reliability, ownership, or frequency.  Examples: all of the current upgrade/downgrade jobs (too flaky), gce-scale-correctness (too infrequent).

**extra**: test jobs whose signal-to-noise ratio it too low for them to be informing, or are too narrow to be blocking, but sometimes are useful to look at for specific things.  Examples: GKE jobs, non-parallel upgrade jobs (if we have any left), maybe some of the conformance jobs.

Note that I've dropped *all* above.  This is because, as CI Signal for 1.13, I found the all board hard to read due to the sheer number of tests on it.  I'd rather have three smaller, exclusive, groups.

So, some spec questions before I start trying to make lists of which jobs belong in which group for approval:

1. Do people agree with the basic division of blocking/informing/extra?

2. Do people agree that "all" is not useful if the tests on it are represented in other groups?

3. Should we have the mature conformance tests on one of these groups?  If so, in informing or extra?

4. Should we even have an "extra" group, given that we might never look at it?

/kind cleanup

attn:
@AishSundar @spiffxp @mariantalla @mortent @BenTheElder @cjwagner

**Comment by jberkus** [comment]
This is to make working decisions for #347

**Comment by spiffxp** [comment]
re: 1,4 - I think we shouldn't have "extra"

re: 2 - sure, I don't think sig-release should have stewardship of all jobs on a release branch, only those jobs they plan on using to decide whether to cut a release, and moving to follow the same blocking/informing pattern would accomplish that

I would prefer patch releases only ever have blocking/informing, rather than expand to three dashboards per release.  I think the currently in development release is the only release that ever gets enough attention merit more than blocking/informing dashboards.  Even then, I am skeptical of the need for an "extra".  If I were CI Signal, I would want fewer things to look at, rather than more stratification.

I would propose:

sig-release-master-*:

- blocking
- kubectl-skew -> these are all sig-cli, move to "sig-cli" dashboard group
- upgrade -> ideally all would become blocking, those jobs that can't move to informing
- upgrade-optional -> these are all gke, I would move to "google" dashboard group as "gke-upgrade"

sig-release-1.y-*:

- blocking, same as before
- all -> (subtract blocking) informing

Then for some specific jobs:

- sig-release-publishing-bot.build -> move to sig-release-misc.publishing-bot-build
- sig-release-misc.cross-build -> move to sig-release-informing.cross-build (I'm not yet convinced it belongs on blocking, but we should be paying more attention to it than we have been)

**Comment by spiffxp** [comment]
re: 3 - I'm not sure what "mature" means in this context

For conformance test jobs, I'm inclined to be strict about the requirements.  None of the conformance jobs currently on release-master-blocking run frequently enough to be on there, and I would at best want them on informing.

**Comment by AishSundar** [comment]
Regarding 1 and 4, I agree with the division except I dont think we need an "extra" dashboard . In my experience in 1.13 cycle, once a job was moved out of blocking, even though we noticed they periodic flake or outright failures and opened issues, we didnt pursue fixes as much as we did for the blocking ones. So while "informing" will definitely be useful (atleast until code freeze), I dont see us paying much attention on the "extra". 

Regarding 2, I dont see the need / use for "all" due to the reason stated above

Regarding 3,  I think Conformance tests are still useful, since they are pretty solid and ,  and should be rolled into "informing", since we dont want vendor specific signals in "blocking"

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/test-infra/issues/11977
