### ISSUE TITLE
Revisit Release Tracking issues

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/sig-release#425]
https://github.com/kubernetes/sig-release/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Release+Tracking

I'm not sure what tool creates these issues, and lack the historical context for when/why we started creating these.  They appear to be created after a build is cut.  AFAICT they have zero human interaction and aren't actually linked to.  Can we get rid of them?

That said, the use of release tracking issues _before_ builds were cut was something I liked during the v1.9 release cycle.  It's unclear to me whether or why we decided to stop using them for future releases.  I'd like to consider bringing these back for v1.14.

**Comment by spiffxp** [comment]
Discussed during release team meeting

@nikhita dug up this for context: https://github.com/kubernetes/release/blob/master/lib/gitlib.sh#L329-L334
```
# Create/update a release tracking issue for posting notifications.
# Mostly for use by --gcb since there's no other email mechanism from which
# to send detailed html notifictions.
# @param version RELEASE_VERSION_PRIME
PROGSTEP[gitlib::update_release_issue]="CREATE/UPDATE RELEASE TRACKING ISSUE"
gitlib::update_release_issue () {
```

No strong opinions for or against using pre-emptive release tracking issues.  I said I would investigate in the 1.9/1.10 retros/notes why the pattern from 1.9 wasn't carried forward

**Comment by spiffxp** [comment]
Summarizing a [thread on #sig-release](https://kubernetes.slack.com/archives/C2C40FMNF/p1547138746179100) with @calebamiles and @dougm 

Posting an issue was a workaround for non-Googlers being unable to send e-mail. The idea being that we could output nicely formatted HTML for them to copy into a release announcement e-mail that they would manually send.  The lifecycle of these issues would then be over.

@dougm said he was able to send e-mail with `release-notify` from kubernetes/release after postfix was properly configured

@calebamiles says we _should_ be able to have GCB send a notification to mailgun to do the same but he hasn't had any time to explore that path

So:
- Let's close the existing Release Tracking issues
- Let's update the branch-manager playbook with the solution that worked for @dougm (or point to an issue that documents what we're going to do instead)
- Let's remove the issue filing code in kubernetes/release

**Comment by calebamiles** [comment]
the summary is more or less correct, however, given that branch management will be a team effort in 1.14 perhaps it just makes the most sense for a Googler (on the team) to send the release announcement email with `release-notify` while working on moving the functionality (not code) back into GCB. Although to be honest the _easiest_ thing to do may just be for a member of the branch management team to copy/paste the email content from the issue and send out the email directly rather than trying to install and properly configure a local MTA (mail transport agent) because it's 2019 not 1989

**Comment by calebamiles** [comment]
1. Yes we can close the release tracking issues
1. I do not believe we should suggest that anyone on the branch management team do anything other than copy the email content from GCS (where it's "staged") into their email tool of choice {Outlook, Gmail, etc}
1. Fine with me to remove the issue filing code.

I do believe that collectively the branch management team should move the functionality back into GCB during the course of the release cycle since it also impacts the work of the patch release management team who will take over the maintenance of the release past .0

**Comment by idealhack** [comment]
cc @hoegaarden the branch manager of 1.14

**Comment by justaugustus** [comment]
Where did we land with this?
I know @spiffxp closed a bunch of issues recently, but are we ready to kill whatever creates the issue?

**Comment by hoegaarden** [comment]
from @spiffxp's list above

> - Let's close the existing Release Tracking issues
> - Let's update the branch-manager playbook with the solution that worked for @dougm (or point to an issue that documents what we're going to do instead)
> - Let's remove the issue filing code in kubernetes/release

I understand there are some issues/PRs for me to create in k/release & k/sig-release and other things to check on:

- investigate sending mail from GCB
- make GCB send mails
  - Note: what are we going to do with debs/rpms? Those are cut out of band, should we still send out a notification? Should we add a section to the mail until the deb/rpm thing is sorted stating something like "packages will come shortly ..."?
- PR to remove the issue creation code from anago

I will try to do that asap.

**Comment by hoegaarden** [comment]
/remove-lifecycle stale

@Bubblemelon the branch manager of 1.15, for visibility

**Comment by hoegaarden** [comment]
Update:

> - investigate sending mail from GCB

[Documentation](https://cloud.google.com/compute/docs/tutorials/sending-mail/#choosing_an_email_service_to_use) suggests, it should be possible to send mails from GCB, just not via the default SMTP port 25.
We can either:
- use a mass mail sending provider like SendGrid, Mailgun, or Mailjet
- use the `kubernetes.io` G Suite account and send via `smtp-relay.google.com: 587`

> - make GCB send mails
>    - Note: what are we going to do with debs/rpms? Those are cut out of band, should we still send out a notification? Should we add a section to the mail until the deb/rpm thing is sorted stating something like "packages will come shortly ..."?

This still needs to be sorted out, package creation & publishing needs to be worked on, so we can get it off-google and into anago (package building as part of `gcbmgr stage ...` & package publishing as part of `gcbmgr release ...`). When this is done, we can automate the full flow, including mail sending, because we don't have any out-of-band process any more we'd need to wait on before announcing a release.

> - PR to remove the issue creation code from anago

Removed with https://github.com/kubernetes/release/pull/669

**Comment by justaugustus** [comment]
Release Managers now create release cut issues pre-release.
Closed via https://github.com/kubernetes/sig-release/pull/519.
/remove-lifecycle rotten
/close
