### ISSUE TITLE
Document kubernetes-release-team Google Groups membership criteria

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/sig-release#458]
/kind documentation
/milestone v1.14
/sig release

My swag before I open a PR:

Who gets to be a member?
- Current release team members
- Current patch release team members

Who gets to be a manager?
- Release team lead

Who gets to be an owner?
- SIG Release leads

**Comment by spiffxp** [comment]
Should shadows be in or out?

**Comment by justaugustus** [comment]
+1 to membership + ACLs as you have them, @spiffxp. Pretty sure that's what I did on the last sweep.
Yes, we should add shadows, though we need to consider the whole disappearing shadow thing and prune often.

**Comment by justaugustus** [comment]
Open for an RT member who wants to take a crack at this.
/help

**Comment by jeefy** [comment]
/assign @lachie83 

@justaugustus Lachie'll take this on unless you really want to :)

**Comment by alejandrox1** [comment]
ping @lachie83 do you have any updates?
/milestone v1.17

**Comment by guineveresaenger** [comment]
Now that I know we're talking about mailing list memberships:

- All Role Leads and Shadows for RT
- SIG release chairs
- Emeritus Advisor

Does Release Management have a separate group? if not, everyone who is on that team too.

RT Lead should update this list at the start of the cycle

Chairs are responsible for making RT Leads managers

**Comment by justaugustus** [comment]
/unassign
/assign @guineveresaenger

> Does Release Management have a separate group? if not, everyone who is on that team too.

We've got our own [lists](https://github.com/kubernetes/sig-release/blob/master/release-managers.md#contact), but yes, current [Branch Managers](https://github.com/kubernetes/sig-release/blob/master/release-managers.md#branch-managers) should be on this list as well to stay abreast on Release Team communications.

> RT Lead should update this list at the start of the cycle

Timing is important here. Some things I've noticed:
- It's easier to prune the list once the next team (including shadows) is locked in (since there may be people returning)
- It's good to figure out any final Release Team communications soon (swag, experience surveys, etc.)
- It's bad to send comms for the next release w/o pruning the prior team (has led to a few moments of confusion/awkwardness for shadows that may not be a part of the next cycle)

> Chairs are responsible for making RT Leads managers

+1

**Comment by alejandrox1** [comment]
Will work on this this week
