### ISSUE TITLE
Move `release-notes` tool under a k-sigs org repo

### ISSUE THREAD

**Issue by jeefy** [kubernetes/sig-release#471]
Currently, the `release-notes` utility used to collate all the release notes for a given release is under a personal repo (https://github.com/marpaia/release-notes) 

As it's now been used for multiple releases, and is the primary utility moving forward, it should probably live under an official k8s repo.

I propose we 
- [ ] Copy code to _existing repo_ (k/release ?) 
- [ ] Update release-notes/README.md with new location
- [ ] Update release notes handbook with new location
- [ ] Thank @marpaia for the awesome tool ;)

**Comment by idealhack** [comment]
If @marpaia agrees, we could migrate the repo by filing an [issue](https://github.com/kubernetes/org/blob/master/.github/ISSUE_TEMPLATE/repo-create.md) against k/org for step one.

**Comment by marpaia** [comment]
I can file the issue to create the repo and move it over, update the imports, etc.

I wonder however if this is the kind of thing we should move to [k/sig-release/release-engineering](https://github.com/kubernetes/sig-release/tree/master/release-engineering)? Perhaps @tpepper or @aleksandra-malinowska have thoughts on this.

**Comment by justaugustus** [comment]
I'm thinking here: https://github.com/kubernetes/release

**Comment by marpaia** [comment]
A had a PR for that up for quite a while but I wasn't able to get any eyes on it: https://github.com/kubernetes/release/pull/575. I can copy it back over there though.

**Comment by jeefy** [comment]
@marpaia That sounds like the best place, I say re-PR it and we'll make sure there's traction.

**Comment by neolit123** [comment]
cc

**Comment by marpaia** [comment]
OK, cool, the PR is up here: https://github.com/kubernetes/release/pull/661

With regards to those other tools, `toolbox/relnotes` was an attempted re-write of the bash `relnotes` tool in Go that hasn't really worked out IMO. I tried to extend it when I was working on my tool, but it's not organized in any library package structure that makes it re-usable. I think we should delete it.

As far as the `relnotes` bash script, this is exec'd by the `anago` shell script when cutting releases. It generates a really minimal, uncontextualized version of release notes and puts it in the CHANGELOG files in k/k. I would love for this to be using the better, contextualized release-notes tool, but really with all this tooling being untestable 1,000+ bash scripts, there is a lot of work to do before these pieces of software can be extended in meaningful ways.

I'll note that I don't want to put down any of the work that people have done, I just don't think that Bash is a good general purpose programming language for objectives which are complicated and require componentization or testing.

So short term, I'd love it if `anago` was shelling out to the `release-notes` Go tool instead of the `relnotes` bash script, but long term, I'd prefer if `anago` was a set of well-tested, well-isolated library code written in Go that was tied together in purpose-built binaries.

**Comment by jeefy** [comment]
This got resolved by https://github.com/kubernetes/release/pull/661 :)
