### ISSUE TITLE
Setup european friendly release-team meeting

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/sig-release#490]
In addition to the current meeting that occurs Mondays in a US friendly timezone (PT).  Previous releases have had one in a European friendly timezone on Tuesdays IIRC.  Now that we have all shadows locked in we have a better idea of our geographic distribution.  

This is not something I personally have the bandwidth to support, so I've asked @marpaia to take point on scheduling and running.

ref: https://github.com/kubernetes/sig-release/issues/411#issuecomment-454112793

/sig release
/area release-team
/milestone v1.14
/assign @marpaia

**Comment by nikopen** [comment]
Thanks!!

**Comment by marpaia** [comment]
The doodle is up, please vote! https://doodle.com/poll/yt9d56qtf47sh49z

**Comment by spiffxp** [comment]
In terms of how to run this, I'm not super sure, how has this been done in the past?  My gut says copying or doing a full agenda might be too much.  

My suggestion: cover the previous day's agenda, and have the EU meeting's agenda consist of Open Discussion notes to capture and questions/comments/concerns that arise.

**Comment by marpaia** [comment]
We had our first EU meeting today! We spent most of meeting talking through yesterdays minutes. When available, a representative of the role provided a summary; Otherwise, I provided a quick summary. We had a brief open discussion as well where the group spoke about v1.13.0-alpha.3, release notes and docs, and the progress of the packaging KEPs.

All in all, I thought it was a nice meeting. Please post here or ping me personally if you were at the meeting (or watch the video) and have feedback on how we can improve!

**Comment by spiffxp** [comment]
/close
Closing as done
