### ISSUE TITLE
Running kubectl commands results in 406 errors

### ISSUE THREAD

**Issue by akirtou** [kubernetes/sig-release#494]
Runnning commands such as get namespaces or get pods results in a "not allowed - 406" error.\
Same commands execute fine on lower kubectl versions. (i.e. 1.10.3)

**Comment by nikhita** [comment]
@akirtou Looks like you are hitting https://github.com/kubernetes/kubectl/issues/533 due to version skew. This should get fixed if you use a client version that is compatible with the server version.

In case the problem persists, please reopen against the kubectl repo. This repo is mainly intended for discussions related to releasing Kubernetes. :)

/close
