### ISSUE TITLE
pre-release announcments should go to k-dev-announce@ and not to k-announce@

### ISSUE THREAD

**Issue by hoegaarden** [kubernetes/sig-release#500]
As per [slack discussion][discussion] `release-notify.sh` should sent mails to `k-dev-announce@` instead of `k-announce@` for alphas, betas, and rc-releases.

- [ ] change `release-notify.sh`
- [ ] update role handbooks and document how to get post permissions for that lists
  - [ ] release branch management
  - [ ] patch release management

Related:
https://github.com/kubernetes/kubernetes/issues/73967
https://github.com/kubernetes/community/issues/3249

[discussion]: https://kubernetes.slack.com/archives/C2C40FMNF/p1549985467043600?thread_ts=1549982448.039400&cid=C2C40FMNF

**Comment by calebamiles** [comment]
why are the automated emails supposed to go to `kubernetes-dev-announce@` now? That list is used by humans on the release team to give early heads up of their plans. The `kubernetes-announce@` mailing list is used by the release tooling to announce the completion of an automated build. The latter has an annoying onboarding mechanism due to the use of Google Groups but such is life. I see no reason to combine or significantly alter the email streams until someone has free time to move this functionality into either GCB or into a standalone app (because yes we can still create new greenfield applications to support the release process).

**Comment by hoegaarden** [comment]
I might have misunderstood the slack discussion,
![image](https://user-images.githubusercontent.com/1401333/52656710-d3adfd00-2eee-11e9-95e2-a36ba93cddde.png)
but I was under the impression we want the following messages to be sent out:
- prod releases: `k-dev@` and `k-announce@`
- non prod releases: `k-dev@` and `k-dev-announce@`

**Comment by justaugustus** [comment]
Yeah, I think the intent was misinterpreted.
@hoegaarden -- can you rename this issue?

The goal here is to document vs change.
When we started that thread, many of us were unsure of the responsibilities of each list.

First and foremost, let's document the current state.

**Comment by hoegaarden** [comment]
Ok. I misunderstood then. Sorry about the confusion.

I think it is documented properly then:
- release branch management: https://github.com/kubernetes/sig-release/blame/master/release-team/role-handbooks/branch-manager/README.md#L36-L37
- patch release management: https://github.com/kubernetes/sig-release/blame/master/release-team/role-handbooks/patch-release-manager/README.md#L65-L67

I will close this issue then.

/close
