### ISSUE TITLE
release lead rolebook addition - swag

### ISSUE THREAD

**Issue by parispittman** [kubernetes/sig-release#605]
hi release team - 

there is a process addition for the role book of the lead:

Leads can request custom release team swag funding, like a tshirt (maybe add links to previous pictures of swag?), to the CNCF ServiceDesk. This tool only has a few people with access so lead will need to work with someone on this list https://github.com/kubernetes/community/tree/master/communication/cncf-servicedesk. 

Note - since the release is quarterly, it may be best to put in for swag as early as possible depending on the date of delivery.

**Comment by justaugustus** [comment]
I'd like this to flow through the SIG Release Chairs, so that there are consistent points of contact across release cycles. Paris suggested I raise this with Steering, since they control who gets on this list (Caleb is already a member). We'll follow up with Steering.

/assign @calebamiles @justaugustus @tpepper 
/milestone v1.15
/priority important-longterm

**Comment by justaugustus** [comment]
We (SIG Chairs) now have access to CNCF Service Desk, so I just need to document this in the Release Team Lead handbook before closing this out.

/remove-lifecycle stale
/unassign @calebamiles @tpepper
/milestone v1.18

**Comment by guineveresaenger** [comment]
hi! following this because I want to make sure I stay up to date
