### ISSUE TITLE
Create a Shadowing Template for all Handbooks

### ISSUE THREAD

**Issue by jberkus** [kubernetes/sig-release#688]
All Handbooks will need a Shadowing section, which describes specifically the main duties of shadows for that role.  A large part of this can be templated from general duties (attend meetings, contact SIGs, etc.), so first step is for me to create that template.

/kind documentation
/assign
/milestone v1.16

**Comment by alejandrox1** [comment]
Lets have the mid-release survey ask shadows if they their handbook has the information needed.

**Comment by lachie83** [comment]
I've had a conversation regarding this with @tpepper. We discussed the history of this issue and the shadow program as a whole and drew the following conclusions regarding this issue:
* This issue was created in the early bootstrap of the shadow program and at that point there wasn't much knowledge or content for the shadows to draw upon.
* When this was created there was a lean towards templating and process creation that is no longer a strong dependency as keeping the documents and process updated is another set of tasks on an extremely focused team.
* There are several documents that the shadows and leads can leverage today for onboarding and orientation making the the creation of these templates not completely necessary.
* I've asked several shadows if templates would help them feel more connected and empowered to succeed in their roles but there was little to no interest.
* The EA role has assumed the responsibility to assist and monitor the shadows.

Overall I don't think this issue is either urgent or important that this stage and would suggest closing and reopening if/when it is both urgent/important

**Comment by jberkus** [comment]
So, do all handbooks now have "Shadow" sections?  

The template wasn't for the shadows.  It was for the leads to update their handbooks.  If all handbooks have been updated, you can close this.

**Comment by JamesLaverack** [comment]
Discussed in 1.24 RT meeting Wednesday 19th January 2022.

We feel this is still needed, and would like to add more verbose documentation for shadows. Possibly re-arrange document, and link from shadow survey.

/assign @jeremyrickard

**Comment by jlbutler** [comment]
Hi all!  This came up in the context of retro and we seem to be addressing the required intent in the [various role handbooks](https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks) as well as the [shadow guidance](https://github.com/kubernetes/sig-release/blob/master/release-team/shadows.md).  I think we are ok to close this one out as suggested a while ago. It can be reopened if needed.
