### ISSUE TITLE
Decide on procedure for jobs entering (and leaving) Blocking

### ISSUE THREAD

**Issue by jberkus** [kubernetes/sig-release#774]
Follow-up to #752 

Currently, we have no established procedure for how a job gets added to Blocking (or Informing), and for that matter what happens when it's removed.  Questions we need to answer are:

1. How does a SIG propose a job for the sig-release boards?
2. Does it start on master-informing or somewhere else?
3. Where do we document why a job was included?
3. Who approves a job being added?
4. When we remove a job from blocking or informing, who gets notified, and where is the removal documented?

attn:
@alejandrox1 @spiffxp @justaugustus 

/kind cleanup
/kind documentation
/milestone v1.16

**Comment by alenkacz** [comment]
I love the proposal @alejandrox1 ❤️ 

Overall owning common jobs/tests that are run before release is a hard problem. I know that many people are fighting this even inside their organizations. I know that we are.

I would love for the toil of CI signal to be spread more among all the SIGs since day 1 I joined the CI signal release team. Establishing a full-blown team inside every SIG for dealing with tests might be too much to ask (?) but I think it would even help if every sig appointed a person or group of people (it could be a rotating role) that would be a frontend to the CI signal work for that SIG for the iteration. It could be for the time of the release or any other period that makes sense.

Apart from the fact that this person would be responsible for also monitoring release jobs belonging to the SIG, it would also be a first line of contact for CI signal release team in case of any test fail triage. 

It actually happened to me recently that we (CI signal release team) was owning a flake in a SIGs job and I could not get hold of anyone in the SIG that would reply to me and help me with deciding the priority or triaging the issue. The messages in the SIGs channel just went unnoticed and I did not really have any other connections within the SIG to push it.

To other topics:

2. yes it should start in informing. We should define rules for that qualifying into blocking (certain amount of failures in a time period)

3. +1 on the documentation

**Comment by soggiest** [comment]
I think this is a great proposal @alejandrox1 

While it will increase the toil on SIG attendees, I believe this is a good path forward to help close the loop between the SIGS and the Release team.

**Comment by alejandrox1** [comment]
Coming back to this...
There have been some recent discussions related to this topic that, in my opinion, make it clear that we need to make "ci signal" a broader effort.
All SIGs are independent entities, there is no SIG to rule them all.
With that on mind, I would like to propose that we enact "ci signal" and contribute with other SIGs as contributors.

To answer the problem statement of this issue: we (sig release) should ask whether they have some CI jobs that offer useful signal for the release or whether we could work with them on building them - ideally the tests that will offer us signal are already built, so for the most part we just need to "build" jobs that will run this.
It is important to keep in mind the differences between tests and jobs. Jobs we can ask for because we want to make sure that things are working. Tests, on the other hand, need insider knowledge. Only the people that work in a pertinent area of the project will know what tests are lacking, which need to be created (this should be part of KEPs already), etc.

There are a couple things we can do to get started:
1. We could rally and occasionally look over the dashboards of other SIGs or drop in their slack channels and ask SIGs what they are doing to test X (if we need a job to test something in specific).
2. Go over enhancements (triage them the way we triage normal issues) and make sure we can see a testgrid link for all of them.
3. Triage the existing tags (i.e.,conformance, serial, slow) for our tests and see if we are missing tests for important behaviors/features.

**Comment by alejandrox1** [comment]
Would people be willing to try that out? I can outright volunteer to do so and to help people learn all that's necessary.

**Comment by hasheddan** [comment]
@alejandrox1 thanks for your work here! I am also happy to volunteer on this effort. A couple of things that stick out to me as potential questions:

- Because there are already a lot of jobs in the `sig-release` dashboards, will we start by auditing what we already have? An alternative could be building out a new set of dashboards with the process you propose, then retiring the current dashboards when we feel that the new ones are stable. I realize this would likely be a lengthy process that would span multiple releases, but it is possible we could organize a team that would be willing to invest a large portion of time into this.
- Could we codify the promotion process of jobs from individual sig dashboards to sig-release and from informing to blocking within sig-release? I know we currently have a number of tools in `test-infra/experiment` that automate various tasks, but it would be cool if we could make this automation a little more robust, potentially even with some sort of visual tracking of the promotion and demotion of jobs.
- Similar to above, could we implement a timeline / cadence for jobs being promoted? Too much process can be inefficient, but it might be helpful to have some hard guidelines that say your test needs to go through "x steps of verification" before being included in the sig-release dashboards.

I likely do not have as much context as some others here, but hopefully these thoughts can be helpful!

**Comment by alejandrox1** [comment]
Update on this: there is an rfc to a proposal to create a CI signal team (independent of the release team), xref https://github.com/kubernetes/sig-release/issues/966.
If that moves forward then there we could potentially enact the policy we proposed here

**Comment by jberkus** [comment]
@alejandrox1 @justaugustus are we going to do anything about this?

**Comment by alejandrox1** [comment]
Reopening 'cas i wanna propose this for the ci signal subproject's charter
/reopen

**Comment by alejandrox1** [comment]
lol life lesson: remove the lifecycle rotten label 
/reopen
/remove-lifecycle rotten
