### ISSUE TITLE
1.18 Shadow Application feedback

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#925]
Opening this issue to capture any feedback from the 1.18 Shadow Application.

/assign @lachie83 
/milestone v1.18
/sig release
/area release-team
/priority important-longterm

**Comment by LappleApple** [comment]
Hi, was there any feedback? Otherwise, can close?

**Comment by lachie83** [comment]
I've had a conversation with @tpepper and confirmed that there have been no changes to the shadow application for since 1.18. 

There was a suggestion by the 1.20 leads to include a question on the applicants preferred pronoun which I add to the 1.20 shadow application and provide to the next EA.

This can be closed.
